from enum import StrEnum

class DisabilityTypeEnum(StrEnum):
    VISION = "VISION"
    HEARING = "HEARING"
    MOBILITY = "MOBILITY"
    COGNITION = "COGNITION"
    SELF_CARE = "SELF_CARE"
    COMMUNICATION = "COMMUNICATION"


class DisabilitySeverityEnum(StrEnum):
    NO_DIFFICULTY = "NO_DIFFICULTY"
    SOME_DIFFICULTY = "SOME_DIFFICULTY"
    A_LOT_OF_DIFFICULTY = "A_LOT_OF_DIFFICULTY"
    CANNOT_DO_AT_ALL = "CANNOT_DO_AT_ALL"


class LanguageSpokenEnum(StrEnum):
    ENGLISH = "ENGLISH"
    HINDI = "HINDI"
    SPANISH = "SPANISH"
    FRENCH = "FRENCH"


class SourceOfIncomeEnum(StrEnum):
    CROP_PRODUCTION = "CROP_PRODUCTION"
    LIVESTOCK_PRODUCTION = "LIVESTOCK_PRODUCTION"
    GOVERNMENT_NGO_SUPPORT = "GOVERNMENT_NGO_SUPPORT"
    OTHERS = "OTHERS"


class LandOwnershipTypeEnum(StrEnum):
    OWNER = "OWNER"
    TENANT = "TENANT"
    CROP_SHARE = "CROP_SHARE"
    FAMILY_GIFT = "FAMILY_GIFT"


class LandSizeUnitEnum(StrEnum):
    HECTARE = "HECTARE"
    ACRE = "ACRE"
    SQUARE_METER = "SQUARE_METER"
    SQUARE_KM = "SQUARE_KM"
    SQUARE_FOOT = "SQUARE_FOOT"
    SQUARE_YARD = "SQUARE_YARD"


class CurrentLandUseEnum(StrEnum):
    AGRICULTURAL = "AGRICULTURAL"
    RESIDENTIAL = "RESIDENTIAL"
    GRAZING = "GRAZING"
    FOREST = "FOREST"


class FarmingTypeEnum(StrEnum):
    CROP = "CROP"
    LIVESTOCK = "LIVESTOCK"
    MIXED = "MIXED"
    AQUACULTURE = "AQUACULTURE"
    AGROFORESTRY = "AGROFORESTRY"


class CropEndUseEnum(StrEnum):
    FOOD_HUMAN_CONSUMPTION = "FOOD_HUMAN_CONSUMPTION"
    FEED_ANIMALS = "FEED_ANIMALS"
    BIOFUELS_NONFOOD = "BIOFUELS_NONFOOD"
    OTHER = "OTHER"


class LivestockSystemEnum(StrEnum):
    NOMADIC_PASTORAL = "NOMADIC_PASTORAL"
    SEMI_NOMADIC = "SEMI_NOMADIC"
    SEDENTARY_PASTORAL = "SEDENTARY_PASTORAL"
    MIXED = "MIXED"
    INDUSTRIAL = "INDUSTRIAL"


class FarmerClusterRoleEnum(StrEnum):
    LEAD = "LEAD"
    DEPUTY = "DEPUTY"
    SECRETARY = "SECRETARY"
    ACCOUNTANT = "ACCOUNTANT"
    MEMBER = "MEMBER"

class EducationalLevelEnum(StrEnum):
    ILLITERATE = "ILLITERATE"
    CAN_READ_AND_WRITE = "CAN_READ_AND_WRITE"
    BASIC = "BASIC"
    INTERMEDIARY = "INTERMEDIARY"
    HIGHER_EDUCATION = "HIGHER_EDUCATION"


class IdTypeEnum(StrEnum):
    UID = "UID"
    RID = "RID"
    NATIONAL_ID = "NATIONAL_ID"
    FARMER_ODK_ACK_ID = "FARMER_ODK_ACK_ID"
    MEMBER_ODK_ACK_ID = "MEMBER_ODK_ACK_ID"
    OTHER = "OTHER"


class IdStatusEnum(StrEnum):
    VALID = "VALID"
    INVALID = "INVALID"


class ConsentTypeEnum(StrEnum):
    BASELINE = "BASELINE"
    SPECIFIC = "SPECIFIC"


class ConsentOriginEnum(StrEnum):
    BENEFICIARY = "BENEFICIARY"
    AGENT = "AGENT"
    STAFF = "STAFF"
    PARTNER = "PARTNER"


class ConsentStatusEnum(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVOKED = "REVOKED"
    DENIED = "DENIED"
    EXPIRED = "EXPIRED"


class FarmerLandOwnershipEnum(StrEnum):
    OWNER = "OWNER"
    TENANT = "TENANT"
    HYBRID = "HYBRID"


class PhoneTypeEnum(StrEnum):
    # Matches the ATI Odoo source (g2p_ati/models/phone_number.py), which
    # extends g2p.phone.number with exactly these three types.
    PRIMARY = "PRIMARY"
    SECONDARY = "SECONDARY"
    OTHER = "OTHER"


class FarmerStateEnum(StrEnum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class FarmerImportSourceEnum(StrEnum):
    INTAKE_FORM = "INTAKE_FORM"
    IMPORT_FILE = "IMPORT_FILE"
    PARTNER = "PARTNER"
    STAFF_PORTAL = "STAFF_PORTAL"
    BENEFICIARY_PORTAL = "BENEFICIARY_PORTAL"
    AGENT_PORTAL = "AGENT_PORTAL"
    VERIFIABLE_CREDENTIAL = "VERIFIABLE_CREDENTIAL"
